### ISSUE TITLE
Cepces status: CA_UNCONFIGURED

### ISSUE THREAD

**Issue by SamdyPrum** [openSUSE/cepces#14]
We have installed and configured cepces/certmonger but after run command request certificate it got error **CA_UNCONFIGURED**

Command: sudo getcert request -c cepces-ca -w -v -M 644 -T Machine -I Computer -k computer.key -f computer.crt

Anyone can help me plz

Thanks,

**Comment by SamdyPrum** [comment]
Error log:

sudo journalctl -xe -t certmonger | tail
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28836]:     raise RuntimeError(
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28836]: RuntimeError: Missing "global/poll_interval" variable in configuration.
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]: Traceback (most recent call last):
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:   File "/usr/libexec/certmonger", line 63, in main
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:     config = Configuration.load(global_overrides=global_overrides,
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:   File "/usr/local/lib/python3.10/dist-packages/cepces-0.3.4-py3.10.egg/cepces/config.py", line 146, in load
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:     return Configuration.from_parser(config)
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:   File "/usr/local/lib/python3.10/dist-packages/cepces-0.3.4-py3.10.egg/cepces/config.py", line 160, in from_parser
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]:     raise RuntimeError(
៦ 01 15:16:26 ITPSAMDY.sabay.office certmonger[28841]: RuntimeError: Missing "global/poll_interval" variable in configuration.

**Comment by dmulder** [comment]
Check the Certification Authority for failed requests. It will give you more detail as to why the request was rejected.

**Comment by dmulder** [comment]
I've gotten CA_UNCONFIGURED, and it was because the CA rejected the key size or something.
