### ISSUE TITLE
setup.py install not respecting prefix

### ISSUE THREAD

**Issue by drlamb** [openSUSE/cepces#22]
Following [this change](https://github.com/openSUSE/cepces/commit/0d6401a1912370010e81943c81737b4276615a26) setup.py install results in bin/cepces-submit being copied to build/bdist.linux-x86_64/egg/libexec/certmonger rather than the intended /usr/local/libexec/certmonger regardless of what prefix I specify. What am I doing wrong?

Modifying the data_files variable path within setup.py to include "/usr/local" works as it did before of course but I'd like to know the intended use of user-definable prefixes. 

I've attempted:

- python3 setup.py install --prefix=/usr/local
- setup.cfg defining the prefix

Test system(s):
Ubuntu 20.04.5 LTS

**Comment by dmulder** [comment]
@cryptomilk could you address this, since you made the breaking change?

**Comment by cryptomilk** [comment]
Then I would suggest to completely remove the data_files. Normally this is meant to install stuff into /usr/share not for config files or libexec.

**Comment by h3po** [comment]
Now the cepces-submit script is not installed at all when --prefix is not given
