### ISSUE TITLE
Wiki and documentation update/expansion

### ISSUE THREAD

**Issue by adam-kosseck** [openSUSE/cepces#28]
**Summary**: Can I please request an update to the wiki/documentation and some assistance?

For the last few days I've been trying to setup and document a test environment to test cepces and have been running into issues.

When trying to refer to the wiki documentation it seems to be quite out of date.
e.g.:
* The wiki mentions a file that doesn't exist anymore (cepces-submit.conf.dist) and doesn't mention the logging.conf.dist file.
* Best practise for pip3 usage is now `python3 -m pip xxx`
* Python requirements have changed
* Updates for RHEL 8/9, Ubuntu 18/20/22.
* The scenarios page is missing.
* Only tested against Windows Server 2012.

I've drafted a build instruction which covers:
* Building 3x Windows Server 2022 VMs
** Configuring the first as an Active Directory Domain Controller
** Configuring the second as a CA
** Configuring the third as a member server, to test CEP from Windows 
* Building a RHEL 8 server VM
** Joining to AD
** Installing certmonger, cepces and all requirements
** Configuring cepces

Unfortunately my instruction is incomplete.  The Windows side seems to be 95% as Windows cert enrollment clients are working,  however certificate requests on RHEL 8 are failing with a 401 "unauthorized for url" error when pointing to the CA CEP_kerberos endpoint.  I'm at a loss as to how to proceed.

I think my document would form a great basis for your missing wiki "Scenarios" page, if it can be finished.  Is there anyone who would be willing to help me fix & finalise my configuration and adapt the documentation I have written so that it is suitable for this wiki?

**Comment by dmulder** [comment]
Are you familiar enough with github wikis that I could give you write access? I'm happy to add you as a contributor if you want to improve the wiki.
Or would you prefer to send me your changes and I can add them?

**Comment by adam-kosseck** [comment]
Github wikis specifically? No, but wikis in general yes.
Happy to update the wiki.

**Comment by adam-kosseck** [comment]
I checked out the wiki code, created a branch and updated it locally.
Unfortunately I do not seem to have the rights to commit my changes to openSUSE/cepces.wiki.

**Comment by dmulder** [comment]
I just granted you rights to push. Let me know if you have any trouble.

**Comment by adam-kosseck** [comment]
Ok I have pushed branch "28" for the wiki.  I can't seem to see a way in the Github UI to view the wiki code/branches, but it should be there.
Please take a look and let me know what you think.  If you can see anything obvious in the instructions as to why cepces is not currently working with my environment, please let me know as I've hit a dead end.

**Comment by dmulder** [comment]
I've merged your changes into master.
