### ISSUE TITLE
Certmonger issues after adding ca

### ISSUE THREAD

**Issue by PierreGode** [openSUSE/cepces#29]
Output from certmonger service in Ubuntu 22

Dec 07 21:50:50 selt20809 certmonger[22025]:     raise RuntimeError(
Dec 07 21:50:50 selt20809 certmonger[22025]: RuntimeError: Missing "global/endpoint" variable in configuration.
Dec 07 21:50:55 selt20809 certmonger[22258]: Traceback (most recent call last):
Dec 07 21:50:55 selt20809 certmonger[22258]:   File "/home/pge/cepces/bin/cepces-submit", line 64, in main
Dec 07 21:50:55 selt20809 certmonger[22258]:     config = Configuration.load(global_overrides=global_overrides,
Dec 07 21:50:55 selt20809 certmonger[22258]:   File "/usr/local/lib/python3.10/dist-packages/cepces-0.3.7-py3.10.egg/cepces/config.py", line 156, in load
Dec 07 21:50:55 selt20809 certmonger[22258]:     return Configuration.from_parser(config)
Dec 07 21:50:55 selt20809 certmonger[22258]:   File "/usr/local/lib/python3.10/dist-packages/cepces-0.3.7-py3.10.egg/cepces/config.py", line 170, in from_p>
Dec 07 21:50:55 selt20809 certmonger[22258]:     raise RuntimeError(
Dec 07 21:50:55 selt20809 certmonger[22258]: RuntimeError: Missing "global/endpoint" variable in configuration.

**Comment by dmulder** [comment]
This error says you're endpoint variable is empty in your cepces.conf. Is it?

**Comment by dmulder** [comment]
Your cepces.conf should be located in `/etc/cepces/cepces.conf`

**Comment by PierreGode** [comment]
So I don know if this is a Ubuntu issue, but after cloning this repository and installing requirements and running the install I do not have /etc/cepces folder, I created the folder manually and I copied my cepces.conf from the cloned folder to etc/cepces/ that worked better, got som issues with certmonger complaining not being able create keytab, but after a couple of restart of the sevice I got status SUBMITTING
