### ISSUE TITLE
updating copr/PPA repositories / wiki references

### ISSUE THREAD

**Issue by randomizer3000** [openSUSE/cepces#6]
The wiki for this project still mentions installation via ufven named repositories despite the project being now managed via openSUSE
dnf copr enable ufven/cepces
add-apt-repository ppa:ufven/cepces

Ideally these should be updated to be openSUSE/cepces and the wiki documentation updated as well

As a separate question is there a plan for a 0.3.5 release would love to have a release for #5 
and [replaced token with requested_token](https://github.com/openSUSE/cepces/commit/73b553bf4ca583dc9768ebd37d97d4c302f02d0d)

**Comment by dmulder** [comment]
I don't own the repo, and I'm unfamiliar with copr. @ufven could you take a look at updating this?

In regard to a release, yes I'd like to do a release, and get your patch in. I'd also like to address the delegation issue mentioned in #4.

**Comment by ufven** [comment]
I'll take a look at it in a few days, currently out of town.

Those repositories are still using the old code repositories. I'll make an effort to update them.

**Comment by dmulder** [comment]
Redhat was recently expressing interest in supporting this for their customers, fyi. They could possibly be working on this also.
@cryptomilk Do you know if anything has been done to update cepces in Fedora?

**Comment by dmulder** [comment]
Considering #23 reports cepces 0.3.5 on RHEL, I think this has finally been resolved.
